### PR TITLE
Update README.md, install.sh, and webcopilot

### PR DESCRIPTION
**Pull request by 0x71rex**
- Update README.md to reflect newly added tools
- Update install.sh:
	* Update most of the tools installation command
	* Replace [sublist3r](https://github.com/aboul3la/Sublist3r) with [SUBLIST3R_V2.0](https://github.com/hxlxmjxbbxs/SUBLIST3R_V2.0)
	* Replace [gau](https://github.com/lc/gau)/[gauplus](https://github.com/bp0lr/gauplus), and [waybackurls](https://github.com/tomnomnom/waybackurls) with [waymore](https://github.com/xnl-h4ck3r/waymore)
	* Switch back to [gau](https://github.com/lc/gau) ([gauplus](https://github.com/bp0lr/gauplus) - discontinued)
	* Update Garud path for lfi.txt payload and gf patterns
	* Update amass_linux_i386 installation to new version (commented out)
- Update webcopilot:
	* Switch Sublist3r (commented out) with SUBLIST3R_V2.0
	* Switch gauplus (commented out) with gau
	* Switch gau/gauplus, and waybackurls (commented out) with waymore

### CODE REVIEW

**Comment by 0x71rex** [comment]
- [Fix](https://github.com/h4r5h1t/webcopilot/issues) #3 - Continue #6
- Add URO #8
- Update README.md, install.sh, and webcopilot #9 
* Update README.md to reflect newly added tools
* Update install.sh:
        a. Update most of the tools installation command
        b. Replace [sublist3r](https://github.com/aboul3la/Sublist3r) with [SUBLIST3R_V2.0](https://github.com/hxlxmjxbbxs/SUBLIST3R_V2.0)
        c. Replace [gau](https://github.com/lc/gau)/[gauplus](https://github.com/bp0lr/gauplus), and [waybackurls](https://github.com/tomnomnom/waybackurls) with [waymore](https://github.com/xnl-h4ck3r/waymore)
        d. Switch back to [gau](https://github.com/lc/gau) ([gauplus](https://github.com/bp0lr/gauplus) - discontinued)
        e. Update Garud path for lfi.txt payload and gf patterns
        f. Update amass_linux_i386 installation to new version (commented out)
* Update webcopilot:
        a. Switch Sublist3r (commented out) with SUBLIST3R_V2.0
        b. Switch gauplus (commented out) with gau
        c. Switch gau/gauplus, and waybackurls (commented out) with waymore
        d. Add uro

**Comment by h4r5h1t** [comment]
Could you please submit the PR to the `dev` branch instead of `main`? Your PR includes a significant number of changes that I'd like to align with the upcoming v2.0 release, along with other planned updates. By targeting `dev`, we can ensure your changes are integrated seamlessly with the v2.0 release cycle.

**Comment by 0x71rex** [comment]
Sure. Thank you.

**Comment by h4r5h1t** [comment]
@0x71rex  Please resolve the conflicts in the `install.sh` file, prioritizing your changes over the previous one. 
Once you've resolved the conflicts, please re-submit the PR so I can review and merge it. 
Thanks for your collaboration! 🙇 🚀

**Comment by 0x71rex** [comment]
No more conflicts I guess

**Pull request merged**
